services:
  mysql-db:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  migrations:
    build: .
    env_file: ./.env
    networks:
      - app-network
    depends_on:
      mysql-db:
        condition: service_healthy
    command: sh -c "yarn prisma migrate deploy && echo 'Migration complete' && exit 0"

  app:
    build: .
    env_file: ./.env
    networks:
      - app-network
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      migrations:
        condition: service_completed_successfully
      mysql-db:
        condition: service_healthy
    command: sh -c "yarn prisma generate && yarn run dev"

networks:
  app-network:

volumes:
  mysql-data:
