import Script from 'next/script'
import localFont from 'next/font/local'

const firaSans = localFont({
  src: [
    {
      path: '../customFonts/FiraSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../customFonts/FiraSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID
  const isProd = process.env.NODE_ENV === 'production'
  return (
    <html lang="en">
      <body className={firaSans.className}>
        {isProd && gaId && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`}
              strategy="afterInteractive"
            />
            <Script id="ga-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${gaId}');
              `}
            </Script>
          </>
        )}
        {children}
      </body>
    </html>
  )
}
